"""removed rate ans desc columns from comments

Revision ID: 67fc5aad799d
Revises: 8be91c2e7b6b
Create Date: 2024-07-15 14:50:09.116912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67fc5aad799d'
down_revision = '8be91c2e7b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('rate')
        batch_op.drop_column('desc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('rate', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
